services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusion-erp-ui
    ports:
      - "3030:80"  # Exposing port 80 of the container on port 3030 of the host
    networks:
      - webnet
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount nginx.conf to container

networks:
  webnet:
