version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusion-erp-ui
    ports:
      - "3030:80"
    networks:
      - webnet
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  webnet:
